### PR TITLE
Fix number of  contributors

### PR DESCRIPTION
**Pull request by TobiGr**
This should fix the contributors count.
@TheAssassin I am not familiar with Tornado, so I did the best I could. If you want, you can improve the performance - I couldn't because of my lack of knowledge and time.

### CODE REVIEW

**Comment by TheAssassin** [comment]
Why bother `per_page`? Can't you fetch them all at once?

**Comment by TobiGr** [comment]
The limit per page is 100. I just make sure we reach it to have a solid base which we can use to do the calculation.

**Comment by TheAssassin** [comment]
Well, my problem with this is that the requests are made sequentially.

I think I'd opt for some very basic web scraping, parsing the HTML site for that value instead.

**Comment by TobiGr** [comment]
We make just one request to get the number of contributors right now. So if you want, we could just fetch the contributors as done before my changes and append `?per_page=100&page=3` to the url. And if necessary, we can increment the page number by hand.

**Comment by TheAssassin** [comment]
@TobiGr almost done with a very basic web scraping approach

**Comment by TheAssassin** [comment]
Check out #5.

**Pull request closed without merging**
